# MANAGED BY DOTFILES
export PATH=/usr/local/bin:/usr/local/sbin:$PATH:/usr/local/share/python
export NODE_PATH=/usr/lib/local/node:/usr/local/lib/node_modules
export PYWIKBOT2_DIR=/Users/km/projects/rewrite

alias eject='drutil tray eject'
alias opena='open -a'
function notify { terminal-notifier -message $1; }

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi
